# Cross-package parity: R's full-result JSON export must byte-match the
# webtool/Python goldens in python/tests/fixtures/expected/*__result.json.
#
# The goldens are generated by scripts/generate-parity-fixtures.mts from the
# live TypeScript exportResultJson(); Python reproduces them byte-for-byte and
# this file asserts the R package does too. Each golden filename encodes the
# sample and the model: "<sample>__<model>__result.json".
#
# dataset_mock_streaming_platforms is the pre-existing xfail: the webapp's
# row-based loader treats duplicate "Dark Matter" rows as 2 distinct items,
# but the R/Python set-based loader dedupes to 1 (documented in
# test-parity-with-webapp.R). We assert the R output does NOT match its golden.

.fixtures_dir <- function() {
    here <- testthat::test_path()
    candidates <- c(
        file.path(here, "..", "..", "..", "python", "tests", "fixtures", "expected"),
        file.path(here, "..", "..", "fixtures", "expected")
    )
    for (cand in candidates) {
        if (dir.exists(cand)) return(normalizePath(cand))
    }
    NULL
}

DUPLICATE_TITLE_SAMPLES <- "dataset_mock_streaming_platforms"

# Parse "<sample>__<model>__result.json" -> list(sample, model).
.parse_result_fixture <- function(fname) {
    stem <- sub("__result\\.json$", "", fname)
    parts <- strsplit(stem, "__", fixed = TRUE)[[1L]]
    list(sample = parts[1L], model = parts[2L])
}

fixtures_dir <- .fixtures_dir()

if (!is.null(fixtures_dir)) {
    result_goldens <- list.files(fixtures_dir, pattern = "__result\\.json$")
} else {
    result_goldens <- character(0L)
}

for (gname in result_goldens) {
    local({
        parsed <- .parse_result_fixture(gname)
        sample <- parsed$sample
        model  <- parsed$model
        golden <- file.path(fixtures_dir, gname)
        is_xfail <- sample %in% DUPLICATE_TITLE_SAMPLES

        test_that(sprintf("result JSON parity (bytes): %s [%s]", sample, model), {
            skip_on_cran()
            skip_if(is.null(fixtures_dir), "webtool fixtures not available")
            res <- analyze(load_sample(sample), model = model)
            actual <- .result_json_string(res)
            expected <- readChar(golden, file.info(golden)$size, useBytes = TRUE)
            if (is_xfail) {
                expect_failure(expect_identical(actual, expected))
            } else {
                expect_identical(actual, expected)
            }
        })
    })
}

test_that("at least the 5 result-JSON goldens are discovered", {
    skip_on_cran()
    skip_if(is.null(fixtures_dir), "webtool fixtures not available")
    expect_gte(length(result_goldens), 5L)
})
